# swagger_definitions.yaml
definitions:
  BlogPost:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: The unique identifier for a blog post.
        readOnly: true
      title:
        type: string
        maxLength: 50
        description: The title of the blog post.
      text:
        type: string
        format: text
        description: The text content of the blog post.
      category:
        type: string
        maxLength: 50
        description: The category of the blog post.
      thumbnail:
        type: string
        maxLength: 255
        description: URL or path to the thumbnail image for the blog post.

  NewBlogPost:
    type: object
    properties:
      title:
        type: string
        maxLength: 50
        description: The title of the new blog post.
      text:
        type: string
        format: text
        description: The text content of the new blog post.
      category:
        type: string
        maxLength: 50
        description: The category of the new blog post.
      thumbnail:
        type: string
        maxLength: 255
        description: URL or path to the thumbnail image for the new blog post.

  AdminUser:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: The unique identifier for an admin user.
      username:
        type: string
        maxLength: 50
        description: The username of the admin user (unique).
      password:
        type: string
        maxLength: 50
        description: The password of the admin user.

  DiscordMessage:
    type: object
    properties:
      author:
        type: string
        description: The author of the Discord message.
      message:
        type: string
        description: The content of the Discord message.

  AccessToken:
    type: object
    properties:
      access_token:
        type: string
        description: JWT Access Token
      token_type:
        type: string
        description: Type of the token, usually "bearer"
      expires_in:
        type: integer
        format: int64
        description: Token expiration time in seconds
